//! DPSS parity tests against MATLAB R2025a `dpss(N, NW, K)` plus
//! standalone sanity tests (orthonormality, eigenvalue residual,
//! concentration-ratio range, error on under-determined window).
//!
//! Fixtures generated by
//! `DYNAM-O_DesktopApp/scripts/generate_handoff_fixtures.m` and staged
//! into `tests/fixtures/`.
//!
//! Tolerances:
//!   - tapers     <=1e-9 max abs vs MATLAB R2025a
//!   - ratios     <=1e-9 max abs vs MATLAB R2025a
//!   - orthonormality <=1e-12

use multitaper_rs::dpss;
use ndarray::{Array1, Array2};
use ndarray_npy::read_npy;
use std::path::PathBuf;

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

/// Apply scipy/MATLAB sign convention to align tapers before comparison.
fn align_sign(rust: &mut Array2<f64>, reference: &Array2<f64>) {
    let k = rust.nrows();
    let n = rust.ncols();
    for r in 0..k {
        // dot product to decide whether to flip
        let mut dot = 0.0;
        for j in 0..n {
            dot += rust[[r, j]] * reference[[r, j]];
        }
        if dot < 0.0 {
            for j in 0..n {
                rust[[r, j]] = -rust[[r, j]];
            }
        }
    }
}

fn max_abs_diff_2d(a: &Array2<f64>, b: &Array2<f64>) -> f64 {
    assert_eq!(a.shape(), b.shape(), "shape mismatch");
    let mut m = 0.0f64;
    for ((x, y), _) in a.iter().zip(b.iter()).zip(0..) {
        m = m.max((x - y).abs());
    }
    m
}

fn max_abs_diff_1d(a: &Array1<f64>, b: &Array1<f64>) -> f64 {
    assert_eq!(a.len(), b.len(), "length mismatch");
    a.iter()
        .zip(b.iter())
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f64, f64::max)
}

#[test]
fn dpss_matlab_parity_n128_nw2_k3() {
    let (mut tapers, ratios) = dpss(128, 2.0, 3).expect("dpss");
    let mat_tapers: Array2<f64> =
        read_npy(fixtures_dir().join("dpss_n128_nw2_k3_tapers.npy")).expect("load tapers");
    let mat_ratios: Array1<f64> =
        read_npy(fixtures_dir().join("dpss_n128_nw2_k3_ratios.npy")).expect("load ratios");

    assert_eq!(tapers.shape(), &[3, 128]);
    assert_eq!(mat_tapers.shape(), &[3, 128]);
    align_sign(&mut tapers, &mat_tapers);

    let dt = max_abs_diff_2d(&tapers, &mat_tapers);
    let dr = max_abs_diff_1d(&ratios, &mat_ratios);
    assert!(dt < 1e-9, "tapers max abs diff = {} (>= 1e-9)", dt);
    assert!(dr < 1e-9, "ratios max abs diff = {} (>= 1e-9)", dr);
}

#[test]
fn dpss_matlab_parity_n1024_nw4_k7() {
    let (mut tapers, ratios) = dpss(1024, 4.0, 7).expect("dpss");
    let mat_tapers: Array2<f64> =
        read_npy(fixtures_dir().join("dpss_n1024_nw4_k7_tapers.npy")).expect("load tapers");
    let mat_ratios: Array1<f64> =
        read_npy(fixtures_dir().join("dpss_n1024_nw4_k7_ratios.npy")).expect("load ratios");

    assert_eq!(tapers.shape(), &[7, 1024]);
    assert_eq!(mat_tapers.shape(), &[7, 1024]);
    align_sign(&mut tapers, &mat_tapers);

    let dt = max_abs_diff_2d(&tapers, &mat_tapers);
    let dr = max_abs_diff_1d(&ratios, &mat_ratios);
    assert!(dt < 1e-9, "tapers max abs diff = {} (>= 1e-9)", dt);
    assert!(dr < 1e-9, "ratios max abs diff = {} (>= 1e-9)", dr);
}

#[test]
fn dpss_orthonormal() {
    let (tapers, _) = dpss(128, 2.0, 3).unwrap();
    let k = tapers.nrows();
    let n = tapers.ncols();
    for a in 0..k {
        for b in 0..k {
            let dot: f64 = (0..n).map(|j| tapers[[a, j]] * tapers[[b, j]]).sum();
            let expected = if a == b { 1.0 } else { 0.0 };
            assert!(
                (dot - expected).abs() < 1e-12,
                "rows {} {}: dot {} expected {}",
                a, b, dot, expected
            );
        }
    }
}

#[test]
fn dpss_concentration_ratios_in_range() {
    let (_, ratios) = dpss(128, 2.0, 3).unwrap();
    for &r in ratios.iter() {
        assert!(r > 0.0 && r <= 1.0 + 1e-12, "ratio out of (0,1]: {}", r);
    }
    // Monotone decreasing (within numerical noise).
    for i in 0..ratios.len() - 1 {
        assert!(
            ratios[i] + 1e-12 >= ratios[i + 1],
            "ratios non-monotonic at i={}: {} -> {}",
            i, ratios[i], ratios[i + 1]
        );
    }
}

#[test]
fn dpss_eigenvectors_satisfy_tridiag() {
    // Build the symmetric tridiagonal matrix T whose eigenvectors are the
    // Slepian tapers (Percival & Walden 1993 ch. 8) and check T*v = lambda*v
    // for each row of `tapers`. The lambda here is the eigenvalue of T, not
    // the concentration ratio.
    let n = 128usize;
    let nw = 2.0;
    let (tapers, _) = dpss(n, nw, 3).unwrap();

    let diag: Vec<f64> = (0..n)
        .map(|i| {
            let centered = (n as f64 - 1.0 - 2.0 * i as f64) / 2.0;
            centered.powi(2) * (2.0 * std::f64::consts::PI * nw / n as f64).cos()
        })
        .collect();
    let offd: Vec<f64> = (0..n - 1)
        .map(|i| (i as f64 + 1.0) * (n as f64 - 1.0 - i as f64) / 2.0)
        .collect();

    for r in 0..tapers.nrows() {
        let v: Vec<f64> = tapers.row(r).to_vec();
        // T*v
        let mut tv = vec![0.0f64; n];
        for i in 0..n {
            tv[i] = diag[i] * v[i];
            if i > 0 {
                tv[i] += offd[i - 1] * v[i - 1];
            }
            if i + 1 < n {
                tv[i] += offd[i] * v[i + 1];
            }
        }
        // Rayleigh quotient for eigenvalue
        let lambda: f64 = tv.iter().zip(v.iter()).map(|(a, b)| a * b).sum();
        let resid_sq: f64 = tv
            .iter()
            .zip(v.iter())
            .map(|(a, b)| (a - lambda * b).powi(2))
            .sum();
        let resid = resid_sq.sqrt();
        assert!(
            resid < 1e-9,
            "taper {}: ||T*v - lambda*v|| = {} (>= 1e-9)",
            r, resid
        );
    }
}

#[test]
fn dpss_short_window_returns_error() {
    // Under-determined: n=3, k=3 cannot give 3 distinct orthonormal vectors
    // representing meaningful Slepians at NW=2.
    let result = dpss(3, 2.0, 3);
    assert!(result.is_err(), "expected Err for n=3 nw=2 k=3, got Ok");
}
