//! End-to-end spectrogram test against the synthetic-EEG fixture.
//!
//! Runs `compute_spectrogram` on `sim_full_seed42` (a 300 s, 100 Hz EEG
//! sim with injected 1 Hz, 12 Hz and 60 Hz components plus motion
//! artifacts) and asserts:
//!
//!   1. Output shape matches `((freq_range_count), num_windows)`.
//!   2. The 1 Hz slow oscillation and 60 Hz line noise show up as
//!      dominant peaks in the time-averaged power spectrum.
//!   3. The 12 Hz spindle band has detectable energy.
//!
//! The fixture is generated by
//! `DYNAM-O_DesktopApp/scripts/generate_handoff_fixtures.m`.

#![allow(clippy::needless_range_loop)]

use multitaper_rs::{compute_spectrogram, dpss, DetrendMode, SpectrogramParams, Weighting};
use ndarray::Array1;
use ndarray_npy::read_npy;
use std::path::PathBuf;

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

fn argmax_in_band(freqs: &[f64], power: &[f64], lo: f64, hi: f64) -> (f64, f64) {
    let mut best_f = 0.0;
    let mut best_p = f64::NEG_INFINITY;
    for (i, &f) in freqs.iter().enumerate() {
        if f >= lo && f <= hi && power[i] > best_p {
            best_p = power[i];
            best_f = f;
        }
    }
    (best_f, best_p)
}

#[test]
fn sim_full_spectrogram_recovers_injected_peaks() {
    let data: Array1<f64> =
        read_npy(fixtures_dir().join("sim_full_seed42.npy")).expect("load sim_full data");
    assert_eq!(data.len(), 30_000, "expected 300 s @ 100 Hz");

    let fs = 100.0f64;
    // Pass-1 style window: 1 s window, 50 ms step, NW=2, K=3.
    let winsize_s = 1.0;
    let winstep_s = 0.05;
    let n = (winsize_s * fs).round() as usize;
    let (tapers, ratios) = dpss(n, 2.0, 3).expect("dpss");

    let params = SpectrogramParams {
        fs,
        frequency_range: (0.0, 70.0),
        window_params: (winsize_s, winstep_s),
        nfft: 256,
        detrend: DetrendMode::Linear,
        weighting: Weighting::Eigen,
    };

    let out = compute_spectrogram(data.view(), tapers.view(), Some(ratios.view()), &params)
        .expect("spectrogram");

    // Expected window count: floor((30000 - 100) / 5) + 1 = 5981.
    assert_eq!(out.mt_spectrogram.shape()[1], 5981, "num_windows");
    assert!(
        out.mt_spectrogram.shape()[0] > 100,
        "expected >100 freq bins, got {}",
        out.mt_spectrogram.shape()[0]
    );

    // Time-average power across windows for each freq.
    let nfreq = out.mt_spectrogram.shape()[0];
    let nwin = out.mt_spectrogram.shape()[1] as f64;
    let mut avg = vec![0.0f64; nfreq];
    for i in 0..nfreq {
        let mut s = 0.0;
        for j in 0..out.mt_spectrogram.shape()[1] {
            s += out.mt_spectrogram[[i, j]];
        }
        avg[i] = s / nwin;
    }
    let freqs: Vec<f64> = out.sfreqs.to_vec();

    // 1 Hz slow oscillation — peak should be in [0, 2.5] Hz.
    let (f_slow, _) = argmax_in_band(&freqs, &avg, 0.0, 2.5);
    assert!(
        (f_slow - 1.0).abs() <= 1.0,
        "slow-osc peak at {} Hz (expected ~1 Hz)",
        f_slow
    );

    // 12 Hz spindle band — bursty so the time-AVERAGED spectrum is dominated by
    // pink noise. Check locally instead: at each spindle center time (30, 80,
    // 140, 200, 260 s), the dominant 8-16 Hz freq should be near 12 Hz.
    let spindle_centers_s = [30.0_f64, 80.0, 140.0, 200.0, 260.0];
    let stimes: Vec<f64> = out.stimes.to_vec();
    for &c in &spindle_centers_s {
        // Find nearest window to spindle center.
        let j = stimes
            .iter()
            .enumerate()
            .min_by(|(_, a), (_, b)| (**a - c).abs().partial_cmp(&(**b - c).abs()).unwrap())
            .unwrap()
            .0;
        let col: Vec<f64> = (0..nfreq).map(|i| out.mt_spectrogram[[i, j]]).collect();
        let (f_local, _) = argmax_in_band(&freqs, &col, 8.0, 16.0);
        assert!(
            (f_local - 12.0).abs() <= 2.0,
            "spindle peak at center {}s -> {} Hz (expected ~12 Hz)",
            c, f_local
        );
    }

    // 60 Hz line noise aliases to 40 Hz at fs=100 (60 mod 50 = 10 below
    // Nyquist => 100 - 60 = 40 Hz). Peak should be in [35, 45] Hz.
    let (f_line, _) = argmax_in_band(&freqs, &avg, 35.0, 45.0);
    assert!(
        (f_line - 40.0).abs() <= 2.0,
        "line-noise (aliased) peak at {} Hz (expected ~40 Hz)",
        f_line
    );
}
